# Generated by Django 4.0.4 on 2022-06-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinipet', '0002_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
